- readme.md
Github pages shows a 404 when clicking through on this link, though it works with a R
> Make website URL case-sensitive

- config/local.env
- config/staging.sample
- rodan/settings.py
- websocket.ini
Still need to propagate the changes in the rodan-docker repo, and update the server scripts.
> [WIP] Added: SSL Certificates to Rodan.

- rodan/settings.py
> Define EMAIL_USE to False

- rodan/jobs/text_alignment/README.md
- rodan/jobs/text_alignment/image_preprocessing.py
- rodan/jobs/text_alignment/training_new_models/save_text_strips.py
> New model training utilities

- rodan/jobs/register_all_jobs.py
changes from a little while back that should've been pushed to develop
> overhaul exceptions to prevent jobs from quietly failing

- python3-celery/Dockerfile
@p42ul Here is the docker file change! 
Let me know if its working
> OpenCV requirements and set up added to docker file py3

- Makefile
- test-prod-compose.yml
Prod image pull and local test options
> Prod Tools

- python3-celery/Dockerfile
- scripts/install_python3_rodan_jobs
Trying to revert gamera to see if that fixes things
> Revert gamera

- python3-celery/Dockerfile
- scripts/install_python3_rodan_jobs
> Remove extra \

- scripts/install_python2_rodan_jobs
Use tag `v1.0.0` when cloning pixel wrapper
> Use tag when cloning pixel wrapper

- rodan-main/code/rodan/jobs/SAE_binarization/__init__.py
- rodan-main/code/rodan/jobs/background_removal/__init__.py
- rodan-main/code/rodan/jobs/register_all_jobs.py
- rodan-main/code/rodan/settings.py
- scripts/install_gpu_rodan_jobs
Training job finished, but GPU memory not released.
> Debug GPU memory issue

- Makefile
- production.yml
Forgot to change the version number in `production.yml` before merging to master.
> changing version number (oops)

- rodan-main/code/rodan/jobs/text_alignment/perform_ocr.py
- rodan-main/code/rodan/jobs/text_alignment/requirements.txt
This fixes https://github.com/DDMAL/Rodan/issues/671.
> Fix text alignment bug

- docker-compose.yml
- hooks/build
- hooks/push
- nginx/Dockerfile
Change all py3test tags back to nightly
> Revert all tags back to nightly

- production.yml
- rodan-main/code/rodan/__init__.py
Merging: 
Neon and Pixel properly to python3
Fixes to the text alignment fixes. It's fixes all the way down.
> Merging small changes to production

- rodan-main/code/rodan/jobs/Paco_classifier/fast_paco_trainer.py
- scripts/install_gpu_rodan_jobs
> Move optimized Paco trainer to staging

- python3-celery/Dockerfile
> Fix build in `develop`

- rodan-main/code/rodan/jobs/MEI_encoding/build_mei_file.py
Just a simplification of what I was working on earlier this summer to make the code a bit easier to read.
> Simplify the build_mei file to avoid repetition

- rodan-client/README
- rodan-client/code/src/js/Views/LayoutViewWorkflowBuilder.js
- rodan-client/code/src/js/WorkflowBuilderGUI.js
- rodan-client/code/styles/default.scss
- rodan-client/code/templates/template-main_workflowbuilder.html
- rodan-client/local-dev/COPYconfiguration
- rodan-client/local-dev/COPYdocker-composefile
- rodan-client/local-dev/CPCONFIGFILE
Rodan client issue fixes and documentation of locally running rodan client and testing. 
Issue #669 is solved here as well!
> Workflow builder responsiveness fixes

- Makefile
- production.yml
- Optimize container build time and size
- Optimized paco trainer
- Fix gamera's `load_png` and `load_tiff` issue
- Add commands to grab logs from containers
> Merge Release v2.0.6 to develop branch

- rodan-main/code/rodan/serializers/workflow.py
Seems like the issue was a python 2 to 3 porting issue.
We used the older version of iterating through iterators (ids.next() vs next(ids).
Going to build and pull the images to see if this fixes the export issue
> Export workflow fix 

- rodan-main/code/rodan/jobs/Paco_classifier/fast_paco_classifier.py
- rodan-main/code/rodan/jobs/Paco_classifier/fast_paco_trainer.py
- scripts/install_gpu_rodan_jobs
Change input and output port names in fast_paco_classifier.py and fast_paco_trainer.py
Change Paco classifier's tag from v2.0.0 to v2.0.1 to accomodate this name change
Resolve #774
> Resolve #774 Change Paco Classifier input and output port name

- Makefile
- production.yml
- python3-celery/Dockerfile
- rodan-main/code/requirements.txt
- staging.yml
- Revert concurrency back to 10
- Downgrade `importlib` version
- Increase RAM of py3-celery container in production
> Release v2.0.8

- Makefile
- production.yml
- rodan-main/code/rodan/settings.py
- Fix `nginx` permission issue that cause pixel not working
- Increase celery container's RAM to 4G on production
> Release v2.0.9

- rodan-main/code/rodan/admin/helpers.py
Resolves: #829 
py2 to py3 convertion issue regarding string and byte string
> Fix #829 fix django's admin page

- Makefile
- production.yml
- rodan-main/code/rodan/__init__.py
- Resolve Save button's hanging problem.
- Fix admin page on staging and production
> Release v2.0.13

- Makefile
- production.yml
- rodan-main/code/rodan/__init__.py
- Disable pagination on user list. Can assign project to other users.
> Release v2.0.14

- rodan-client/code/src/js/Controllers/ControllerResource.js
> Fix #555, wait for server to return all resources

- rodan-client/code/src/js/Collections/BaseCollection.js
> Fix #555, add async option in BaseCollection

- rodan-main/code/rodan/jobs/MEI_encoding/build_mei_file.py
Resolves: (#901)
- Added type annotations to method parameters to improve maintainability
- Made a few minor changes as to prevent errors during type-checking (adding null checks, etc.)
- MEI output is not modified
- In the future, we can use `TypedDict` to better type `dict` objects but there is some code that would need to be refactored, as in some methods, the same variable is reused for dictionaries with different shapes
> [MEI Encoding] Add type annotations

- rodan-client/code/src/js/Application.js
- rodan-client/code/src/js/Views/Master/LayoutViewMaster.js
- rodan-client/code/templates/Views/Master/template-master.html
Removed some unnecessary divs, and added some css selectors to certain elements in order to be able to add css styles.
> 💄 Minor HTML clean up for rodan-client

- .github/workflows/ci.yml
- ci-jobs/Dockerfile
- rodan-main/code/requirements.txt
- rodan-main/code/rodan/admin/__init__.py
- rodan-main/code/rodan/admin/admin.py
- rodan-main/code/rodan/models/project.py
- rodan-main/code/rodan/models/resource.py
- rodan-main/code/rodan/serializers/runjob.py
- rodan-main/code/rodan/settings.py
- rodan-main/code/rodan/test/views/testIndividual_interactive.py
- rodan-main/code/rodan/urls.py
- rodan-main/code/rodan/views/connection.py
- rodan-main/code/rodan/views/inputport.py
- rodan-main/code/rodan/views/inputporttype.py
- rodan-main/code/rodan/views/interactive.py
- rodan-main/code/rodan/views/job.py
- rodan-main/code/rodan/views/outputport.py
- rodan-main/code/rodan/views/resource.py
- rodan-main/code/rodan/views/resourcelabel.py
- rodan-main/code/rodan/views/resourcelist.py
- rodan-main/code/rodan/views/resourcetype.py
- rodan-main/code/rodan/views/resultspackage.py
- rodan-main/code/rodan/views/runjob.py
- rodan-main/code/rodan/views/userpreference.py
- rodan-main/code/rodan/views/workflowjobgroup.py
- rodan-main/code/rodan/views/workflowrun.py
Resolves: (#900 )
Upgraded a lot of related requirements in the process of this PR. Next I need to update to django 2.1
Everything appears to look good? I have tested locally but want to see how the CI test goes
> Django upgrade to 2.0

- rodan-client/code/styles/default.scss
- rodan-client/code/templates/template-main_workflowbuilder.html
Resolves: (#874)
- Change workflow name and status from links to appropriate elements and style them appropriately
> Workflow name and status should not change appearance on hover

- rodan-client/code/templates/Views/Master/Tables/template-table_control.html
Resolves: (#921)
- Disable form submit action to prevent redirection
> [Client] Prevent redirect on Enter when filtering jobs

- rodan-client/code/src/js/Models/Workflow.js
Resolves: (#844)
- Check that fields exist before iterating to prevent errors when creating new workflow
> [Client] Fix for PR #942

- rodan-main/code/rodan/jobs/load.py
Resolves: (#988 )
add SafeLoader to yaml.load
> fix yaml load with SafeLoader

- scripts/install_gpu_rodan_jobs
> add no-cache-dir tag

- rodan-client/code/src/js/Application.js
- rodan-client/code/src/js/Views/LayoutViewWorkflowBuilder.js
Resolves: (#1022)
- Re-enable disabled ErrorManager
- Include the last error message in the workflow status
> Show workflow error messages

- rodan-main/code/rodan/migrations/0005_auto_20230711_1052.py
> Fix migration conflict

- rodan-client/code/src/js/Controllers/ItemController.js
- rodan-client/code/src/js/Models/Workflow.js
- rodan-client/code/src/js/WorkflowBuilderGUI.js
Resolves: (#993)
- Revert the changes to workflow model parse method from #980 and #981 as it turns out the workflow builder depends on collection item instances remaining the same across updates
- Fix #844 by instead adding an initialization method to handle existing collection items
> [Client] Fix `Ctrl` + `0` not centering workflow in workflow builder

- rodan-client/code/src/js/Behaviors/BehaviorTable.js
- rodan-client/code/src/js/Controllers/ControllerResource.js
Resolves: (#1049)
- Listen to collection `add`, `remove`, and `sync` events and fetch and update label filters
> Update resource label filters on resource collection change

- rodan-client/code/src/js/Behaviors/BehaviorTable.js
- rodan-client/code/src/js/WorkflowBuilderGUI.js
- rodan-client/code/styles/default.css
- rodan-client/code/templates/Views/Master/Navigation/template-navigation.html
- rodan-client/code/templates/Views/Master/Navigation/template-navigation_root.html
Resolves: (#1072)
- Fix the navigation tree overflow issue.
- Update styles to make UI more suitable for smaller laptop screens.
- Minor style changes to workflow builder (canvas)
> UI updates

- python3-celery/Dockerfile
Resolves: (#1044)
Update Gamera tag in Rodan to match gamera4-rodan main branch
> Update gamera tag

- hooks/build
- hooks/post_build
- hooks/push
Resolves: 
**Trigger webhook and send message to Slack**
Set up automated notifications and integrations with Slack bot to forward docker build status to slack channel.
> Trigger webhook and send message to Slack

- scripts/staging.env
> Fix #1100, Update scripts/staging.env

- Makefile
- production.yml
- rodan-main/code/rodan/__init__.py
> Release v3.0.0
