DDMAL/Rodan

- rodan/jobs/core.py
- rodan/jobs/helloworld/helloworld.py
- rodan/jobs/master_task.py
- rodan/test/helpers.py
- rodan/test/views/test_workflowrun.py
- rodan/views/workflowrun.py
A workflow should accept the input of multiple resource collections that share the same length (greater than 1). The engine should iterate through the collections at the same time to produce the workflow run results (much like how Python `zip()` works).
- Loosen the validation of workflowrun creation to multiple resource collections of same length.
- Adapt `core.create_workflowrun` so that it correctly iterates through multiple resource collections when creating objects under the workflowrun.
- Add new hello world job that supports multiple ports for easier testing.
- Fix an outdated error message from workflowrun creation.
- Fix an unreferenced setting `settings.EMAIL_USE` (because it is by default not provided at all in settings.py)
Video: https://vimeo.com/382214288 (password: rodan)
> Workflow execution extension to multiple resource collections

- rodan/views/resource.py
We need to give some information on the resource we are deleting when
responding to client so use a ResourceSerializer to do that.
> Use a ResourceSerializer when deleting a resource

- rodan/jobs/load.py
This can be accompanied by deleting the resource_types.yaml files in the
various jobs. Ideally this should make the Python 3 container run
properly since it (and any other container) has access to all resource
type definitions without needing the jobs to be loaded.
Proper media types are added in comments where applicable (e.g., `application/midi` to `audio/midi`).
> Move resource types to Rodan itself.

- rodan/jobs/core.py
When processing many new image resources at a time it's possible for the celery worker to run out of memory when calling graphics magick when preparing an image for use with diva.js. Rather than fail immediately, this lets the worker retry 3 times and wait 10 seconds each time. Usually by then enough memory will be freed for the process to succeed.
> Reduce occurrances of SIGKILL issue

- rodan/jobs/core.py
- rodan/jobs/deep_eq.py
- rodan/jobs/diva_generate_json.py
- rodan/settings.py
- rodan/test/views/test_resource.py
- rodan/test/views/test_workflow.py
- rodan/test/views/test_workflowrun.py
- rodan/urls.py
- rodan/views/main.py
- rodan/views/resource.py
Creates and serves a zipfile based on requests to the `/api/resources/archive`. GET request with parameters as resource UUIDs results in a zipfile being generated and returned by `rodan.core.create_archive`. ~This is stored in memory for 30 minutes, when it is deleted.~ FileResponse handles deletion of the zipfile from memory.
> Add support for getting resources in zipfile

- .gitignore
- rodan/settings.py
This adds the MEI_resizing job to the excludes in the `rodan/jobs` folder and includes it as a commented out Python2 job.
> Include references to MEI_resizing

- requirements.txt
Updated lxml to 4.6.3 and PyYAML to 5.4 in order to aquire security patches. Tested changes locally in rodan-docker and everything seemed fine, however I'll create a PR into develop rather than commiting so that someone else can test the changes -- don't wanna break the Celery-updated version on a Sunday.
Edit: Couldn't update Pillow and djangorestframework as the secure versions no longer support Python 2.7 -- a familiar story.
> Update requirements.txt to aquire security patches 

- rodan/jobs/text_alignment/align_to_ocr.py
- rodan/jobs/text_alignment/image_preprocessing.py
I was unable to reproduce #618 anywhere outside of Rodan, which doesn't make a lot of sense. I reverted the behavior of the text alignment pre-processing back to how it used to be, and added a bunch of (possibly redundant) conversions to make sure that the `dtype`s of all images are exactly what we expect them to be at each step.
> Reverting text alignment preprocessing flood-fill back to using uint8 only

- gpu-celery/Dockerfile
- python2-celery/Dockerfile
- python3-celery/Dockerfile
Removes the statements of `git clone https://github.com/DDMAL/Rodan.git` from all the dockerfiles, and instead just copies the rodan "core" code directly from within this repository now that it's all unified.
> Remove rodan git clones

- hooks/build
- rodan-main/Dockerfile
- rodan-main/code/rodan/__init__.py
- rodan-main/code/rodan/views/main.py
This PR exposes a new API endpoint called build_hash that tracks the Git commit hash at which `rodan-main` was built.
This is useful for implementing E2E tests, as it gives us a way to understand at which point the code has broken (when it does break).
> Add build_hash to Rodan API

- rodan-main/code/rodan/jobs/background_removal/BgRemovalRodan.py
- rodan-main/code/rodan/jobs/background_removal/__init__.py
- rodan-main/code/rodan/jobs/background_removal/resource_types.yaml
- rodan-main/code/rodan/jobs/register_all_jobs.py
- rodan-main/code/rodan/settings.py
- scripts/install_gpu_rodan_jobs
---
* Job Name: `Background Removal`
* Category: `Background removal - remove image background`
* Containers: `gpu-celery`
* Job Queue: `GPU`
* Input Port Type: `rgb+png`, `rgb+jpg`, `rgba+png`, `greyscale+png`, `onebit+png`
* Output Port Type: `rgba+png`
* Settings:
* `Background Removal Method`: A drop down menu to select the method to do background removal. Support using [Sauvola Threshold](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_niblack_sauvola.html) (no neural network) and [Selectional Auto-Encoder (SAE) binarize](https://github.com/ajgallego/document-image-binarization) (with neural network)
* `window_size`: The `window_size` for Sauvola Threshold, see docs for [`skimage`](https://scikit-image.org/docs/stable/api/skimage.filters.html#skimage.filters.thres …
> Add background removal to rodan jobs

- rodan-main/code/rodan/jobs/SAE_binarization/SAE_binarization.py
- rodan-main/code/rodan/jobs/SAE_binarization/__init__.py
- rodan-main/code/rodan/jobs/SAE_binarization/resource_types.yaml
- rodan-main/code/rodan/jobs/register_all_jobs.py
- rodan-main/code/rodan/settings.py
- scripts/install_gpu_rodan_jobs
> Add SAE binarization removal to rodan jobs

- rodan-main/code/rodan/jobs/background_removal/BgRemovalRodan.py
- scripts/install_gpu_rodan_jobs
1. Add an optional empty output port to rodan job. This is the intput layer to pixel_wrapper.
2. git clone using tag v1.0.0
> Add empty output port to bgRemoval rodan wrapper, clone with tag

- rodan-main/code/rodan/jobs/text_alignment/requirements.txt
Adding a single line to make sure Paul's fork of `tfaip` is only installed in the `gpu-celery` container and not in the rodan-main container, which still uses python2 (for now, anyway!)
> make sure tfaip is not installed in python 2

- production.yml
- staging.yml
Changing the default memory allocation for `production.yml` and `staging.yml` to fix https://github.com/DDMAL/Rodan/issues/670, hopefully
> increase memory allocation for prod, staging

- rodan-main/code/rodan/jobs/hpc_fast_trainer/hpc_fast_trainer.py
this is similar to the gamera error when all jobs are moved to python3 along with their dependencies but rodan-main while register jobs look for the dependencies in python2 container. The try-except clause ignore the dependency import until it's actually running the job in python3 container
> add try except for pika import error

- Makefile
- production.yml
- scripts/start
- scripts/start-celery
Production officially works in python3!
Ended up creating a new branch to avoid all the unecessary back and forth commits but I'll document our work on here.
We had to fix the var permissions to make it not a recursive process. The var folder does however need to be read and writeable due to an error that pops up in text allignment.
Updating the database was a bit trickier. For starters, we needed to have both plpythonu (which defaults to python 2) and plpython3u in the postgres container which seemed counterinuitive. While our code works in plpython3, the database was looking for the plpython2 directory to try to update the old code. Then once the database was updated once, we could remove plpythonu from the postgres container and dockerfile.
The most recent problem we had was an import …
> New production release for python 3!

- gpu-celery/Dockerfile
- python3-celery/Dockerfile
- rodan-main/Dockerfile
- rodan-main/code/requirements.txt
- scripts/install_gpu_rodan_jobs
After https://github.com/DDMAL/Rodan/pull/738 was merged, some dependency issues were introduced into both the build process and the running application. This PR fixes those dependency issues so that the build from the `develop` branch can be built and run without error.
- Fixes #749
> Fix dependency issues caused by py3-celery changes.

- rodan-main/code/rodan/jobs/diva_generate_json.py
Resolve #752 
Resolve DDMAL/pixel_wrapper#53
In Rodan v2.0.4 (SHA:bdb65ce) pixel is seriously broken. Can't even open
small images and always get Server Error 500. This is because the
create_diva job failed after migrating all jobs into python3.
This commit makes create_diva work in py3 by fixing the find() function
and the way to decode image width/height from bytes.
> Fix #752, Fix Server-Error-500 in Pixel

- hooks/build
- hooks/push
This along with a build rule that will be added to dockerhub will allow for us to build off of master. Nothing super complicated, just changed the tag to go with the most recent version of Rodan so dockerhub will build master's images and push them to this tag when needed.
> Build off of master

- hooks/build
- hooks/push
Reverts DDMAL/Rodan#756
This isn't workable in the long run since the build hooks to make rodan-main pull from a `nightly` branch already. Going to find another way to do it.
> Revert "Build off of master"

- python3-celery/Dockerfile
- rodan-main/code/rodan/jobs/Paco_classifier/fast_paco_trainer.py
- scripts/install_gpu_rodan_jobs
- staging.yml
1. In `SAE_binarization`, `background_removal`, and `paco_classifier`, downgrade their python3 requirement from `3.7.5` to `3.7.3`. This is to let them go along with Rodan using python3.
2. In `paco_classifier`, support:
- using a large zip file containing tiny zip files as the training data
- let users decide the `patience` parameter
- optimized `v.2.0.0` paco, which requires less training time
3. Increase the RAM size in `gpu-celery`  container
4. Update pixel tag
> Update paco classifier to v2.0.0

- Makefile
Resolve #668 
1. `make gpu-celery_log` to fetch `rodan-celery-GPU.log` from `rodan_gpu-celery` container.
2. `make py3-celery_log` to fetch `rodan-celery-Python3.log` from `rodan_py3-celery` container.
3. `make celery_log` to fetch `rodan-celery-celery.log` from `rodan_celery` container.
4. `make rodan-main_log` to fetch `rodan.log` from `rodan_rodan-main` container.
> Fix #668, fetch logs from containers

- python3-celery/Dockerfile
Resolves #764 
load_png and load_tiff are not working because of the missing `_png_support.cpython-37m-x86_64-linux-gnu.so` and `_tiff_support.cpython-37m-x86_64-linux-gnu.so` in `ddmal/rodan-python3-celery`. But `_png_support.cpython-38m-x86_64-linux-gnu.so` and `_tiff_support.cpython-38m-x86_64-linux-gnu.so` do exist in `ddmal/gamera4:latest`.  Things went wrong when building `rodan-python3-celery` (py3.7) from `ddmal/gamera` (py3.8).
This PR solves this issue by downgrading the python version in `ddmal/gamera4` to 3.7 to solve this issue. Changes in this PR:
1. Downgrade `ddmal/gamera4`'s python3 version to 3.7. See [ddmal/gamera4-rodan](https://github.com/DDMAL/gamera4-rodan/commit/3ef2a48029b02f588ec84aa20849a1038977f0e1).
2. Use `ddmal/gamera4:v1.0.1`tag from docker hub. This is …
> Fix #764, Downgrade gamera container to py37

- python3-celery/Dockerfile
- rodan-main/code/rodan/jobs/Paco_classifier/resource_types.yaml
- rodan-main/code/rodan/jobs/mei2vol_wrapper/resource_types.yaml
Resolves #772 
Change descriptions in the `resource_types.yaml` in the these jobs: `Paco_classifier`, `mei2vol_wrapper`, and `pixel_wrapper`, to remove the message:
```
Multiple descriptions found for <type>: 
#1: <description 1>
#2: <description 2>
...
Choose a description (#1, #2, ...) or enter yours: ...
```
These messages show up when using `MIGRATE=True python3 manage.py migrate --noinput` or `./manage.py test`
> Fix #772, Remove multiple descriptions

- rodan-main/code/rodan/jobs/Paco_classifier/fast_paco_trainer.py
Resolve #775 Move the zip section above the preprocessing section which adds .npy files. Added checks for input ports.
> Fix #775 Paco multizip

- rodan-main/code/requirements.txt
Resolves #782 
The v5.0.0 importlib-metadata causes import error in celery. Downgrade its version to v4.12.0
> Fix #782, Restrict importlib version

- production.yml
- python3-celery/Dockerfile
- staging.yml
GPU-related jobs are not in py3-celery container. Try to increase the concurrency to run multiple py3 jobs parallelly. Increase memory or else py3-celery container will be stopped by oom_reaper.
> Fix #769, Set concurrency to 10 in py3-celery

- rodan-main/code/rodan/settings.py
Resolves #787 
The permission for original_file (the original image) is 600 and the owner is root. This causes permission denied/403 forbidden error when pixel_wrapper tries to read the input layer and triggers nginx to read the origina_file as www-data user. This violates the permission and causes the issue.
Solution: Since running nginx subprocess as root is risky, this commit sets the uploaded file permission to 644 so both root and www-data can read the file.
> Fix #787, Fix permission denied issue in nginx

- rodan-main/code/rodan/jobs/text_alignment/align_to_ocr.py
- rodan-main/code/rodan/jobs/text_alignment/image_preprocessing.py
- rodan-main/code/rodan/jobs/text_alignment/perform_ocr.py
Think this addresses https://github.com/DDMAL/Rodan/issues/779 by tweaking how the black background removal step works so that it doesn't flood-fill the entire manuscript with white occasionally - added sanity checks to several steps in the process, just to make sure it doesn't crash (unless it has to, and then it provides a better error message).
> Fix text alignment 

- production.yml
- staging.yml
Resolves #796 
Since the concurrency in celery and py3-celery is 10, there will be at least 10 large images using RAM at the same time. We need more RAM to do so.
> Fix #796, Increase RAM in celery and py3-celery container

- python3-celery/Dockerfile
- staging.yml
Resolves #797 
- Loose the health-check condition in rodan-main/celery/py3-celery or else they are shut down from time to time and cause hanging jobs.
- Reduce the concurrency in celery/py3-celery
- Increase cpus in celery, decrease cpuys in gpu-celery
> Fix #797, loose health check condition on staging

- production.yml
Resolves #797 on production
1. Loose the healthcheck policy in `rodan-main`, `celery`, and `py3-celery`. Before this pull request (PR) the conditions are quite strict:
```
rodan-main:
healthcheck:
interval: "10s"   # Do health check every 10 seconds
timeout: "5s"     # Need to get the response in 5 seconds. If not, it fails the health check
retries: 2        # Restart rodan-main when it fails two times in a roll
celery:
healthcheck:
test: ["CMD", "celery", "inspect", "ping", "-A", "rodan", "--workdir", "/code/Rodan", "-d", "celery@celery"]
interval: "30s"
timeout: "10s"
start_period: "1m"
retries: 3
py3-celery:
healthcheck:
test: ["CMD", "celery", "inspect", "ping", "-A", "rodan", "--workdir", "/code/Rodan", "-d", "celery@Python3"]
interval: "30s"
timeout: "10s"
retries: 3
gpu-celery: …
```
> Fix #797, loose health check condition on production

- rodan-main/code/rodan/jobs/pil_rodan/red_filtering.py
Resolves #804 
Some images are read as the P mode which raises error in the autocontrast function. Convert the input image to RGB mode to avoid this issue.
> Fix #804, Convert the input image to RGB mode

- rodan-main/code/rodan/jobs/text_alignment/requirements.txt
Changes the `tfaip` version to one hosted locally in the DDMAL organization. This fixes #806.
> Update text-alignment reqs to fix tfaip

- postgres/Dockerfile
Resolves #808 
Postgres no longer supports debian stretch. Therefore, upgrade it from stretch (postgres:9.6) to bullseye (postgres:9.6-bullseye)
> Fix #808, Upgrade from Debian stretch to bullseye in postgres

- python3-celery/Dockerfile
> Fix #814, Install specific versions of npm and yarn

- python3-celery/Dockerfile
- rodan-main/Dockerfile
- scripts/start-celery
Resolves #813 
Celery does not release memory after finishing jobs and causes the out-of-memory issue. Jobs will be killed by oom-reaper and hangs forever in Rodan. Restart workers to release memory.
Rules to restart workers in containers:
`py3-celery`: 12G memory on staging and production, 3 workers and restart each worker after doing one job.
`celery`: 12G memory on staging and production, 6 workers and restart each worker after doing 5 jobs.
`gpu-celery`: 8G memory on staging, 45G memory on production, 1 worker and restart each worker after doing one job.
> Fix #813, Restart workers to release memory

- Makefile
- production.yml
1. Fix the hanging job problem in staging and production by
-  Loose containers' healthcheck policy
-  Restart workers to release memory
2. Pin npm version to 8.10.0-r0 in python3-celery image
3.  Add CI tests for rodan functionalities and jobs
4. Fix the mode problem in Red filtering
5. Remove invalid input port types in Masking
> Release v2.0.11 to develop

- scripts/healthCheckFromUrl.sh
Resolves #781 
Send notification mails when staging/prod website is down. Healthcheck is performed at `00:00`, `06:00`, `12:00`, `18:00`
Usage: `bash healthCheckFromUrl.sh <URL>`
Use curl to access a URL. If it fails, send a notification email to addresses in `MAIL_LIST`.
This script is located in `/root `and scheduled in `/etc/crontab`
Steps to use this script (only do this in production):
1. Add your email address to `MAIL_LIST` with format `<mail 1>;<mail 2>;<mail 3>;...`
2. `chmod 744 healthCheckFromUrl.sh`
3. `chown root accessFromUrl.sh`
4. `chgrp root accessFromUrl.sh`
5. move this script to /root
6. Add this to `/etc/crontab`: `0  0,6,12,18  * * *   root    /root/healthCheckFromUrl.sh https://rodan-staging.simssa.ca/`
7. Add this to `/etc/crontab`: `0  0,6,12,18  * * *   root …
> Fix #781, Add cron job to check rodan's website

- scripts/install_gpu_rodan_jobs
Resolves: #822 
Use v2.0.2 tag in Paco classifier. Sort keys first so data loaders are used in the correct order `(Layer 0, Layer 1, ...)`
> Fix #822, train and save ckpts in the correct order

- Makefile
- production.yml
- rodan-main/code/rodan/__init__.py
Release v2.0.12 for staging
- Save paco's trained ckpts in the correct order
- Periodically check production and staging websites to know they're still up
- Add testcase for MEI encoding, Heuristic Pitch Finding, and Non-interactive classifier
> Release v2.0.12 for staging

- rodan-client/code/src/js/WorkflowBuilderGUI.js
- rodan-client/local-dev/arm-compose.yml
- rodan-client/readme.md
Resolves: #635 
`Save` button does not work after entering and quitting workflow canvas. This is because the workflow canvas uses `paper.js`, which overrides the default `Event` class, while the `Save` button tries to use the default `Event` class.
Solve this issue by reloading the default Event class back when leaving the workflow canvas
> Fix #635, Save button failed after entering workflow canvas

- rodan-main/code/rodan/views/user.py
Resolves: #771 
Some users are on the second page, so they do not appear in the drop-down menu. Disable pagination so users are on one page
> Fix #771, disable pagination to show users in one page

- rodan-main/code/rodan/jobs/Calvo_classifier/__init__.py
Upon trying to run the new images locally I found that there was a lingering reference to the fast_calvo_trainer job which caused issues when running. This should fix it!
> Remove a reference to fast calvo trainer 

- Makefile
- readme.md
- rodan-client/readme.md
- rodan-main/code/rodan/jobs/heuristic_pitch_finding/README.md
- starter.sh
Resolves: (#870)
Fix the `docker-compose` in the documentations and readmes inside Rodan codebase to `docker compose`
> Fix docker-compose docs inside Rodan

- rodan-main/code/rodan/jobs/MEI_encoding/build_mei_file.py
Resolves: (#869)
- Update `build_mei_file.py` so that `clef` and `accid` elements can now be contained inside `syllable` elements as per 5.0.0-dev
- Simplify if conditions to improve readability
> [MEI Encoding] Incorrect Version

- ci-jobs/Dockerfile
- python3-celery/Dockerfile
- rodan-main/code/rodan/jobs/interactive_classifier/interactive_classifier.py
Resolves: (#860)
- use a quick-fix version of gamera with docker tag fix_IC
- commented out decode in interactive_classifier.py to work with the new gamera image
> fix IC with another gamera tag

- rodan-client/code/src/js/Behaviors/BehaviorTable.js
- rodan-client/code/src/js/Controllers/ControllerResource.js
- rodan-client/code/src/js/Models/Resource.js
- rodan-client/code/src/js/Shared/RODAN_EVENTS.js
- rodan-client/code/src/js/Views/Master/Main/Resource/Individual/ViewResourceMulti.js
- rodan-client/code/src/js/Views/Master/Main/ResourceLabel/ViewResourceLabel.js
- rodan-client/code/templates/Views/Master/Main/Resource/Collection/template-main_resource_collection_item.html
- rodan-client/code/templates/Views/Master/Main/Resource/Collection/template-modal_resource_collection_item.html
- rodan-client/code/templates/Views/Master/Main/Resource/Collection/template-modal_resource_collection_item_assigned.html
- rodan-client/code/templates/Views/Master/Main/Resource/Individual/template-main_resource_individual.html
- rodan-main/code/rodan/serializers/resource.py
- rodan-main/code/rodan/views/resource.py
Resolves #555 
When loading resources, for each resource, we currently fetch a list of all labels. We now include the complete label when serializing resources so there is no longer a need to make a separate request for each resource. As a result, only a single request needs to be made. This improves performance, user experience, and reduces server load.
> No longer fetch label for each resource seperately

- rodan-client/code/src/js/WorkflowBuilderGUI.js
Resolves #727, #856
- Prevent the browser default behaviour of zooming in the page when the zoom shortcuts are pressed on Windows
> [Client] Fix zoom shortcuts

- Makefile
Resolves: (#937)
fix `make run_arm`
> Fix #937, Fix run_arm in Makefile

- rodan-client/code/styles/default.scss
💄 Changed Rodan modal-window opacity from 0.88 to 1.
Resolves: (#871)
All modal windows in Rodan will now have an opacity value of 1. 
The reason this change was requested: It's sometimes hard to see and read things in the modal windows because of the opacity settings. Additionally, there doesn't seem to be any important reason for having slightly transparent modal windows.
> Fix for modal-window opacity

- rodan-main/code/rodan/admin/helpers.py
- rodan-main/code/rodan/settings.py
- rodan-main/code/rodan/views/project.py
- scripts/local.env
Resolves: (#934)
This PR resolves some minor bugs caused by the django 1.11 to 2.0 migration. 
1. In django 2.0 `MIDDLEWARE_CLASSES` was changed to `MIDDLEWARE` which was causing the hard refresh issue. 
2. Users were able to see projects that they did not have permissions to see and this was resolved by filtering out projects based on permissions 
3. Updated authentication handling in the Django admin page to address an issue introduced in Django 2.0.13
> Django 2.0.13 Migration Fixes

- rodan-client/code/src/js/Behaviors/BehaviorTable.js
- rodan-client/code/src/js/Configuration.js
- rodan-client/local-dev/CPCONFIGFILE
Resolves: (#925)
- Set a short timer before making a request and reset the timer each time a keystroke is made so that a request is made only when the user is finished typing
> Wait for the user to stop typing before making a search request

- rodan-main/code/rodan/views/workflow.py
Resolves: (#498 )
Include if else in workflow.py to only check for `WFJ_TOO_MANY_IP` or `WFJ_TOO_MANY_OP` when maximum port is not set to 0. According to the [Wiki](https://github.com/DDMAL/Rodan/wiki/Write-a-Rodan-job-package#1-describe-a-rodan-job), the maximum ports of 0 indicates no maximum requirement.
> Fix 0 port requirement issue

- rodan-client/code/src/js/Controllers/ControllerUserPreference.js
- rodan-main/code/rodan/serializers/user.py
- rodan-main/code/rodan/serializers/userpreference.py
Resolves: (#460)
- Add `user_preference` field in user serializer and use it to fetch user preference by id
> No longer fetch all user preferences

- rodan-client/code/src/js/Models/Workflow.js
Resolves: (#844)
This PR changes how the workflow model is parsed so that it does not directly modify attributes, as that is not a recommended practice in backbone. Instead it creates new collections and returns the parsed response. 
This resolves the issue of workflows appearing empty in the workflow builder as the collection add event is triggered for every job, port, etc. of the workflow. These events are what trigger the creation of the items on screen. Previously, updates would cause some or all of these events to be missed, resulting in the workflow builder being empty.
> Fix empty workflow builder after user edits workflow name or description

- e2e/rodan_connection.py
Resolves: #960
After minor UI updates last year, there are two elements with the same text (`Workflow`), so Selenium is confused.
Resolve this by searching elements by ID.
> Fix end-to-end test with selenium

- rodan-client/code/src/js/Controllers/ControllerResource.js
Resolves: (#977)
- Check and update the correct field (`this.collection_no_page` instead of `this.collection`)
> [Client] Fix error when reopening input port select resource modal

- rodan-main/code/rodan/views/job.py
- rodan-main/code/rodan/views/project.py
- rodan-main/code/rodan/views/resource.py
- rodan-main/code/rodan/views/runjob.py
- rodan-main/code/rodan/views/userpreference.py
- rodan-main/code/rodan/views/workflow.py
- rodan-main/code/rodan/views/workflowjobgroup.py
- rodan-main/code/rodan/views/workflowrun.py
Resolves: (#982 )
I added some ordering for the querysets in the rodan views to prevent the filtering warnings that come up in the docker logs. I only modified the files that were throwing the warnings, there may be more filtering that needs to happen in the future
> Order querysets to avoid inconsistent results warning 

- rodan-main/code/rodan/jobs/interactive_classifier/ic_frontend/public/js/app/App.js
By resetting the array on the save event, we ensure that the same glyphs are not sent to the backend on consecutive clicks of the save button. I have run Sabrina's tests outlined in #955 as well as other tests for Revert and Reclassify, and all functionality seems to work as intended with this change.
Resolves: (#955)
> Modify IC frontend to flush grouped glyphs on save function

- gpu-celery/Dockerfile
Resolves: #1005
cuda 11.2.1 is no longer supported. Upgrade to cuda 11.2.2
> Fix #1005, Change cuda to 11.2.2

- rodan-main/code/rodan/jobs/column_split/__init__.py
- rodan-main/code/rodan/jobs/column_split/base.py
- rodan-main/code/rodan/jobs/column_split/column_split.py
- rodan-main/code/rodan/registerJobs.yaml
Implements a job when given a folio with multiple columns and the output from Paco's, it returns new layers with the columns stack. Addresses https://github.com/DDMAL/Rodan/issues/828. Tested on [Tours, F-TOm 149](https://cantus.simssa.ca/manuscript/146/).
The algorithm uses the vertical projection of the staff layer. It works as follows: for i in the range of columns: find the highest point on the projection. Find the points to the left and right with value 0. Consider that a column and remove it from the projection. After finding the column ranges, split them up then stack them.
This has been tested on 10 folios from Tours, F-TOm 149](https://cantus.simssa.ca/manuscript/146/), all of which worked really well. Here are some example layers from different …
> Add column splitting job

- rodan-main/code/rodan/jobs/MEI_encoding/MEI_encoding.py
- rodan-main/code/rodan/jobs/MEI_encoding/build_mei_file.py
Implements support for multi-column folios in mei encoding as well as reversing the splitting done by the new column splitting job. Currently multi-column folios are not supported in Neon.
All lines of code related to multiple columns are wrapped in an "if multi_column" block, so for regular folios this has no affect.
> Multi-column MEI encoding/unsplitting

- rodan-client/code/src/js/Controllers/ControllerWorkflowJobGroup.js
- rodan-client/code/src/js/WorkflowBuilderGUI.js
Resolves: (#1011)
- Modify methods to calculate bounding boxes in WorkflowBuilderGUI to be reused in ControllerWorkflowJobGroup 
- Use the centre of selected workflow jobs instead of the canvas when creating new job groups
> Center new workflow job groups

- rodan-client/code/src/js/Views/Master/Main/InputPort/ViewInputPortCollectionItem.js
- rodan-client/code/src/js/Views/Master/Main/InputPortType/ViewInputPortTypeCollectionItem.js
- rodan-client/code/src/js/Views/Master/Main/OutputPort/ViewOutputPortCollectionItem.js
- rodan-client/code/src/js/Views/Master/Main/OutputPortType/ViewOutputPortTypeCollectionItem.js
- rodan-client/code/templates/Views/Master/Main/InputPort/Collection/template-main_inputport_collection_item.html
- rodan-client/code/templates/Views/Master/Main/InputPortType/Collection/template-main_inputporttype_collection.html
- rodan-client/code/templates/Views/Master/Main/InputPortType/Collection/template-main_inputporttype_collection_item.html
- rodan-client/code/templates/Views/Master/Main/OutputPort/Collection/template-main_outputport_collection_item.html
- rodan-client/code/templates/Views/Master/Main/OutputPortType/Collection/template-main_outputporttype_collection.html
- rodan-client/code/templates/Views/Master/Main/OutputPortType/Collection/template-main_outputporttype_collection_item.html
Resolves #857 
- For each port type, display current number of ports and disable add/delete button according to min/max
> [Client] Limit add/delete ports to min/max

- rodan-main/code/rodan/jobs/pil_rodan/to_png.py
When converting from RGBA-png to RGB, transparent information sometimes gets inverted. This fix helps the conversion for rgba-png to be consistent. See more here: https://github.com/DDMAL/pixel_wrapper/issues/86
Resolves: (https://github.com/DDMAL/pixel_wrapper/issues/86)
> Fix PNG (RGB) job

- rodan-client/code/src/js/Controllers/ControllerModal.js
- rodan-client/code/src/js/Managers/ErrorManager.js
Resolves: (#1058)
- Change modal error messages to either display a specified message or simply "An unknown error occured.", rather than dumping the contents of the JSON response
> Fix modal error messages

- rodan-main/code/rodan/jobs/interactive_classifier/ic_frontend/public/js/app/auth/Authenticator.js
Resolves: #600
This resolves the unnecessary credential prompt when the app is opened.
> Update IC authenticator to read token from cookies

- rodan-main/code/rodan/jobs/base.py
Resolves: (#1029)
- Fix typo in send workflow failure email function
> Fix typo in sending workflow failure emails

- Makefile
- Add default tags when doing make pull
Resolves: #1088
> Fix #1088, Fix make pull

- nginx/scripts/start
Resolves: #1087 
* Can't talk to iipsrv:9003 so comment out that line
* Need to specify the port when trying to connect to rodan-client
* Wait for 900 secs when establishing tcp connection with rodan-main
> Fix #1087, Fix nginx's start script

- iipsrv/Dockerfile
- nginx/scripts/start
> Fix #1093, Fix iipsrv start script

- iipsrv/Dockerfile
> Fix #1093, Fix iipsrv port

- rodan-client/code/styles/default.css
Fixes #1102 by setting the maximum width of the model window.
Resolves: #1102
Set the maximum width of the model dialog.
> Fix text overflow in pop-up window

- .github/workflows/release-bot.yml
Fix #1103 so testers know what to test for a new release
> feat: Create a feature checklist on release

- rodan-main/code/rodan/jobs/heuristic_pitch_finding/StaffFinding.py
Fix #1124
- adjust initial condition for staff finding
- make sure the blackness will decrease by 0.05 when previous try did not work
- make sure the algorithm finds more than one spot
- handle worst case when gamera fails and raise exception here to avoid error msg in later jobs
- output message for successful or failed  staff finding
- remove old codes
- tested on Einsiedeln 158v, 168r, 269v (which failed in original code) and 059v
Resolves: (#1124)
> fix: rewrite StaffFinding while loop and clean up

- rodan-client/code/styles/default.css
Resolves: #1146
1. use `fr` unit for `grid-template-columns`
2. make only `tbody` scroll on overflow
> Adjust modal window grid and fix scroll

- rodan-main/code/rodan/jobs/interactive_classifier/interactive_classifier.py
Resolves: #1179
The class name, when comes from training xml, is of type bytes. It was decoded but it was the original one that was added to the `name_set`. Updated to adding the decoded name.
> Solve name_set type error in interactive classifier

- build.yml
- gpu-celery/Dockerfile
Resolves: (#1185)
Fixed Dockerfile for gpu-celery container where pip install was no longer supported for python < 3.8 with the old link.
Removed duplicate iipsrv block in build.yml.
ci/dockercloud-stage should work again.
> Fix gpu dockerfile

- rodan-main/code/rodan/jobs/base.py
- rodan-main/code/rodan/jobs/extract_c_clefs/__init__.py
- rodan-main/code/rodan/jobs/extract_c_clefs/base.py
- rodan-main/code/rodan/jobs/extract_c_clefs/extract_c_clefs.py
- rodan-main/code/rodan/registerJobs.yaml
This PR adds a Rodan job that crops C Clefs from an image, given the PNG image file and an XML file generated from the Interactive Classifier job. 
The output resources of this job are PNG images of C clefs, named with the original image filename and indexed.
> Add C Clef Extraction Job

- rodan-main/code/rodan/jobs/core.py
- rodan-main/code/rodan/views/resource.py
Resolves: (#1180)
We changed the IO package and added encoding and decoding steps to make batch downloading work on resources page.
> Fix batch downloading

- scripts/install_gpu_rodan_jobs
Paco tag v2.0.4 has two newer commits to main, which fixed the training algorithm, and the same requirement.txt as the previous v2.0.3.
Resolves: (#1209)
Our Rodan now should point to the latest Paco codes. All changes are captured in the tag v2.0.4 with the currently used, fixed dependencies, and the fix for the inference step in the classifying job. (Please refer to the issue for more details.)
Kyrie and I have tested the new docker images on our local machine and grid lines are no longer there with the same model.
> Fix paco classifying and update paco code repo tag to v2.0.4

- Makefile
- production.yml
- rodan-main/code/rodan/__init__.py
- Fix setting: alpine version in iipsrv
- Fix setting: pip install source url in gpu dockerfile
- Fix setting: tag update for fixed PACO code
- Fix UI: resource assignment modal window layout
- Fix UI: modal window grid
- Fix UI: scroll
- Fix UI: modal window styles
- Fix UI: clear view on workflow delete
- Fix job: StaffFinding adaptive blackness threshold
- Fix job: IC type error
- Fix job: batch downloading
- Fix job: heuristic pitch finding default octave
- Fix job: Miyao staff finding test file
- New feature: extract c clef job
- New feature: rename in resource distributor
Merge release v3.1.0 into develop with new changes since v3.0.0.
> Release v3.1.0
